export const KEYBOARD = {
  a: { isAccidental: false, frequency: 261.63 },
  w: { isAccidental: true, frequency: 277.18 },
  s: { isAccidental: false, frequency: 293.66 },
  e: { isAccidental: true, frequency: 311.13 },
  d: { isAccidental: false, frequency: 329.63 },
  f: { isAccidental: false, frequency: 349.23 },
  t: { isAccidental: true, frequency: 369.99 },
  g: { isAccidental: false, frequency: 392.00 },
  y: { isAccidental: true, frequency: 415.30 },
  h: { isAccidental: false, frequency: 440.00 },
  u: { isAccidental: true, frequency: 466.16 },
  j: { isAccidental: false, frequency: 493.88 },
  k: { isAccidental: false, frequency: 523.25 },
  o: { isAccidental: true, frequency: 554.37 },
  l: { isAccidental: false, frequency: 587.33 },
  p: { isAccidental: true, frequency: 622.25 },
  ";": { isAccidental: false, frequency: 659.25 },
  "'": { isAccidental: false, frequency: 698.46 },
};